export enum AuthActionTypes {
    AUTH_START = "AUTH_START",
    AUTH_SUCCESS = "AUTH_SUCCESS",
    AUTH_FAIL = "AUTH_FAIL",
    AUTH_LOGOUT = "AUTH_LOGOUT",

    CLEAR_ERROR = "CLEAR_ERROR",
}

export enum QueueActionTypes {
    FETCH_QUEUE_START = "FETCH_QUEUE_START",
    FETCH_QUEUE_SUCCESS = "FETCH_QUEUE_SUCCESS",
    FETCH_QUEUE_FAIL = "FETCH_QUEUE_FAIL",

    ADD_TO_QUEUE_START = "ADD_TO_QUEUE_START",
    ADD_TO_QUEUE_SUCCESS = "ADD_TO_QUEUE_SUCCESS",
    ADD_TO_QUEUE_FAIL = "ADD_TO_QUEUE_FAIL",

    DELETE_FROM_QUEUE_START = "DELETE_FROM_QUEUE_START",
    DELETE_FROM_QUEUE_SUCCESS = "DELETE_FROM_QUEUE_SUCCESS",
    DELETE_FROM_QUEUE_FAIL = "DELETE_FROM_QUEUE_FAIL",

    DONE_IN_QUEUE_START = "DONE_IN_QUEUE_START",
    DONE_IN_QUEUE_SUCCESS = "DONE_IN_QUEUE_SUCCESS",
    DONE_IN_QUEUE_FAIL = "DONE_IN_QUEUE_FAIL",
}

export enum SubjectActionTypes {
    FETCH_SUBJECTS_START = "FETCH_SUBJECTS_START",
    FETCH_SUBJECTS_SUCCESS = "FETCH_SUBJECTS_SUCCESS",
    FETCH_SUBJECTS_FAIL = "FETCH_SUBJECTS_FAIL",

    ADD_SUBJECT_START = "ADD_SUBJECT_START",
    ADD_SUBJECT_SUCCESS = "ADD_SUBJECT_SUCCESS",
    ADD_SUBJECT_FAIL = "ADD_SUBJECT_FAIL",

    EDIT_SUBJECT_START = "EDIT_SUBJECT_START",
    EDIT_SUBJECT_SUCCESS = "EDIT_SUBJECT_SUCCESS",
    EDIT_SUBJECT_FAIL = "EDIT_SUBJECT_FAIL",

    DELETE_SUBJECT_START = "DELETE_SUBJECT_START",
    DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS",
    DELETE_SUBJECT_FAIL = "DELETE_SUBJECT_FAIL",
}

export enum PlacementActionTypes {
    FETCH_PLACEMENTS_START = "FETCH_PLACEMENTS_START",
    FETCH_PLACEMENTS_SUCCESS = "FETCH_PLACEMENTS_SUCCESS",
    FETCH_PLACEMENTS_FAIL = "FETCH_PLACEMENTS_FAIL",

    ADD_PLACEMENT_START = "ADD_PLACEMENT_START",
    ADD_PLACEMENT_SUCCESS = "ADD_PLACEMENT_SUCCESS",
    ADD_PLACEMENT_FAIL = "ADD_PLACEMENT_FAIL",

    EDIT_PLACEMENT_START = "EDIT_PLACEMENT_START",
    EDIT_PLACEMENT_SUCCESS = "EDIT_PLACEMENT_SUCCESS",
    EDIT_PLACEMENT_FAIL = "EDIT_PLACEMENT_FAIL",

    DELETE_PLACEMENT_START = "DELETE_PLACEMENT_START",
    DELETE_PLACEMENT_SUCCESS = "DELETE_PLACEMENT_SUCCESS",
    DELETE_PLACEMENT_FAIL = "DELETE_PLACEMENT_FAIL",
}